name: Azure Static Web Apps CI/CD

on:
  schedule:
  - cron: "*/5 * * * *"

jobs:
  build_and_test_job:
    runs-on: ubuntu-latest
    name: Build and test Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build 11ty
        run: |
          npm install
          npm run build
