---
name: Testing tests repeatedly
'on':
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "*/5 * * * *"

jobs:

  clickonstuff:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Build 11ty
        run: |
          npm install
          npm run build
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: npm test
        run: |
          npm test