name: Testing tests less

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  build_and_test_job:
    name: Build and test job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build 11ty
        run: |
          npm install
          npm run build
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: npm test
        run: |
          npm test
        env:
          CI: true
